name: lali
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  easy_localization: ^3.0.3
  carousel_slider: ^5.1.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  firebase_core: ^3.15.2
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.1
  firebase_remote_config: ^5.3.2
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.10
  firebase_storage: ^12.4.10
  firebase_in_app_messaging: ^0.8.1+10
  flutter_html: ^3.0.0-beta.2
  flutter_staggered_animations: ^1.1.1
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.1.0
  geocoding: ^2.0.0
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.5.1
  html: ^0.15.4
  html_unescape: ^2.0.0
  http: ^1.1.2
  flutter_stripe: ^10.2.0
  razorpay_flutter: ^1.3.5
  image_picker: ^1.0.6
  intl: ^0.20.2
  launch_review: ^3.0.1
  line_icons: ^2.0.3
  lottie: ^2.0.0
  package_info_plus: ^8.3.1
  provider: ^6.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  skeleton_text: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  toast: ^0.3.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.12
  permission_handler: ^11.2.0
  flutter_custom_clippers: ^2.1.0
  animated_text_kit: ^4.2.2
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  mime: ^1.0.4
  open_filex: ^4.3.4
  path_provider: ^2.1.2
  uuid: ^4.3.3
  flutter_firebase_chat_core: ^1.6.7
  file_picker: ^10.3.2

dependency_overrides:
  # Force web-compatible versions to fix Flutter web build errors
  cached_network_image_web: ^1.2.0
  image_picker_platform_interface: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tb.png"

# The following section is specific to Flutter packages.
flutter:

  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/seed/

  

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
