// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLFZZH-sOOihtO4KLROaaaxaGRbd8copw',
    appId: '1:791241718220:web:0c7b9df5b3ece5574e4569',
    messagingSenderId: '791241718220',
    projectId: 'lali-faef2',
    authDomain: 'lali-faef2.firebaseapp.com',
    storageBucket: 'lali-faef2.firebasestorage.app',
    measurementId: 'G-LMYY5EYWQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4eI6Tx_yvXfdvBe3aJ0pz2egy9fREo8',
    appId: '1:791241718220:android:8522321736eb24874e4569',
    messagingSenderId: '791241718220',
    projectId: 'lali-faef2',
    storageBucket: 'lali-faef2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARFUgAz47JnCMpO7dO_srax447BIlOJu0',
    appId: '1:791241718220:ios:0fa1b1ff8010c53e4e4569',
    messagingSenderId: '791241718220',
    projectId: 'lali-faef2',
    storageBucket: 'lali-faef2.firebasestorage.app',
    iosClientId: '791241718220-vknkgt04b6hgtb66cp1blq25eh0qboqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.lali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARFUgAz47JnCMpO7dO_srax447BIlOJu0',
    appId: '1:791241718220:ios:99169fde0fcd94ff4e4569',
    messagingSenderId: '791241718220',
    projectId: 'lali-faef2',
    storageBucket: 'lali-faef2.firebasestorage.app',
    iosClientId: '791241718220-cehene9qr8v5v457sd3brare9g17038r.apps.googleusercontent.com',
    iosBundleId: 'com.example.lali.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLFZZH-sOOihtO4KLROaaaxaGRbd8copw',
    appId: '1:791241718220:web:5a736188459ba7c04e4569',
    messagingSenderId: '791241718220',
    projectId: 'lali-faef2',
    authDomain: 'lali-faef2.firebaseapp.com',
    storageBucket: 'lali-faef2.firebasestorage.app',
    measurementId: 'G-L9SBBJY1P6',
  );

}