name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter pub get
        run: flutter pub get
      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - name: Test
        run: flutter test --coverage || true
      - name: Build APK (debug)
        run: flutter build apk --debug
      # For release builds and store uploads, add signing keys as GitHub secrets and uncomment below:
      # - name: Build AAB (release)
      #   run: flutter build appbundle --release
